name: flutster
description: Record your Flutter UI tests using this Widget. Save the UI tests to play them again automatically.
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_compare:
  flutter_test:
    sdk: flutter
  share_plus: ">=4.0.4"
  http:
  intl:

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: li.jod.flutster
        pluginClass: FlutsterPlugin
