name: flutster
description: Record your Flutter UI tests using this Widget on Android. Save the UI tests to play them again automatically.
version: 1.0.2
homepage: https://github.com/jod-li/flutster
repository: https://github.com/jod-li/flutster
issue_tracker: https://github.com/jod-li/flutster/issues

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  image_compare: ">=1.1.2 <2.0.0"
  flutter_test:
    sdk: flutter
  share_plus: ">=6.3.1 <7.0.0"
  http: ">=0.13.4 <1.0.0"
  intl: ">=0.18.0 <1.0.0"
  cross_file: ">=0.3.3+4 <1.0.0"

dev_dependencies:
  flutter_lints: ">=2.0.1 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: FlutsterTestRecorder