name: flutster
description: Record your Flutter UI tests using this Widget on Android. Save the UI tests to play them again automatically.
version: 1.0.1
homepage: https://github.com/jod-li/flutster
repository: https://github.com/jod-li/flutster
issue_tracker: https://github.com/jod-li/flutster/issues

environment:
  sdk: ">=2.20.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_compare: ^1.1.2
  flutter_test:
    sdk: flutter
  share_plus: ^4.0.10
  http: ^0.13.4
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: FlutsterTestRecorder